type Mutation {

    register(user: UserInput!): ResultRegister!
    updateUser(user: UserInput!): ResultUser!
    deleteUser(id: ID!): ResultUser!
    # añadir los generos de los juegos

    addGenre(genre: String!): ResultGenre!
    updateGenre(genre: GenreInput!): ResultGenre!
    deleteGenre(id: ID!): ResultGenre!
}