type Query {

    users(page: Int = 1, items: Int = 20): ResultUser!
    login(email:String!, password: String!): ResultLogin!
    me: ResultUser!
    genres(page: Int = 1,items: Int = 20 ): ResultGenre!
    # se va a paginar de 20 en 20
    # se dejan los datos por default sino se envia nada
    genre(id: ID!): ResultGenre!
}