type Query {
  "Crear toeken para relizar los pagos por tarjeta"
  createCardToken(card: CardInput): ResultStripeCard!
  retrieveCard(customerId: String!, cardToken: String!): ResultStripeCard!
  listCards(
    customerId: ID!
    limit: Int = 5
    "Especificar la primera posicion despues la seleccion del usuario"
    startingAfter: ID = ""
    "Terminar antes de este usuario para mostrar los anteriores"
    endingBefore: ID = ""
  ): ResultStripeCard!
}
