type Query {
  customers(
      limit: Int = 5
      "Especificar la primera posicion despues la seleccion del usuario"
      startingAfter: ID = ""
      "Terminar antes de este usuario para mostrar los anteriores"
      endingBefore: ID = ""
  ): ResultStripeCustomer!
  # Obtener los detalles del cliente
  # ID del cliente de Stripe
  customer(id: ID! ): ResultStripeCustomer!
}
