type ResultUser implements Result { # al heredar los datos de la interfaz debe implementar los campos de la interfaz
    info: ResultInfo
    status: Boolean!
    message: String!
    users: [User!]
}